# Site settings
title: Brittany Harris
email: hello@brittany-harris.com
description: Brittany Harris is a front end developer with a lot of feelings about cats, the internet, and cats on the internet.

baseurl: ""
url: "http://brittany-harris.com"
twitter_username:   brittharr
github_username:    brittharr
instagram_username: brittharr_
linkedin_username:  brittharr
version: 2.0.0
permalink: /blog/:year/:month/:day/:title/

collections:
  work:
    output: true
    permalink: /work/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown_ext:  markdown,mkdown,mkdn,mkd,md

exclude: ['node_modules', 'gulpfile.babel.js', 'package.json', 'Gemfile', 'Gemfile.lock']

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
