# Site settings
title: Brittany Harris
email: bjh3ev@virginia.edu
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brittany-harris.com" # the base hostname & protocol for your site
twitter_username:   brittharr
github_username:    brittharr
instagram_username: brittharr_
linkedin_username:  brittany-harris/30/1b5/7a8
version: 2.0.0

collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
