# Site settings
title: Brittany Harris
email: hello@brittany-harris.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brittany-harris.com" # the base hostname & protocol for your site
twitter_username:   brittharr
github_username:    brittharr
instagram_username: brittharr_
linkedin_username:  brittany-harris/30/1b5/7a8
version: 2.0.0
permalink: /blog/:year/:month/:day/:title/

collections:
  work:
    output: true
    permalink: /work/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

exclude: ['node_modules']

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "highlight", "footnotes", "smart"]

sass:
  style: compressed

gems:
  - jekyll-redirect-from
