# Site settings
title: Brittany Harris
email: hello@brittany-harris.com
description: Brittany Harris is a front end developer with a lot of feelings about cats, the internet, and cats on the internet.

baseurl: ""
url: "http://brittany-harris.com"
twitter_username:   brittharr
github_username:    brittharr
instagram_username: brittharr_
linkedin_username:  brittharr
version: 2.0.0
permalink: /blog/:year/:month/:day/:title/

collections:
  work:
    output: true
    permalink: /work/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

exclude: ['node_modules']

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "highlight", "footnotes", "smart"]

sass:
  style: compressed

gems:
  - jekyll-redirect-from
