name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.5.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build --if-present
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          keep_history: true
          allow_empty_commit: true
          build_dir: build
          committer: Brittany Harris <hello@brittany-harris.com>
          author: Brittany Harris <hello@brittany-harris.com>
          commit_message: Update brittany-harris.com
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
